-- problem 2
{-
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
[1, 2, 3, 5, 8, 13, 21, 34, 55, 89...]
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
-}
limit :: Integer
limit = 4000000

fibs = 1 : 2 : zipWith (+) fibs (tail fibs)

fibSum :: Integer -> Integer
fibSum limit = sum [x | x <- takeWhile (<= limit) fibs, even x]

main :: IO ()
main = do
    let sum' = fibSum limit
    print sum'